package com.example.barbershopproject.model.enumeration;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum City {
  SOFIA("Sofia"),
  PLOVDIV("Plovdiv"),
  VARNA("Varna"),
  BURGAS("Burgas"),
  RUSE("Ruse"),
  STARA_ZAGORA("Stara Zagora"),
  PLEVEN("Pleven"),
  SLIVEN("Sliven"),
  DOBRICH("Dobrich"),
  SHUMEN("Shumen"),
  PERNIK("Pernik"),
  YAMBOL("Yambol"),
  HASKOVO("Haskovo"),
  PAZARDZHIK("Pazardzhik"),
  BLAGOEVGRAD("Blagoevgrad"),
  VELIKO_TARNOVO("Veliko Tarnovo"),
  VRATSA("Vratsa"),
  GABROVO("Gabrovo"),
  VIDIN("Vidin"),
  ASENOVGRAD("Asenovgrad"),
  KYUSTENDIL("Kyustendil"),
  KARDJALI("Kardjali"),
  KAZANLAK("Kazanlak"),
  MONTANA("Montana"),
  DIMITROVGRAD("Dimitrovgrad"),
  LOVECH("Lovech"),
  TARGOVISHTE("Targovishte"),
  SILISTRA("Silistra"),
  DUPNITSA("Dupnitsa"),
  RAZGRAD("Razgrad"),
  GORNA_ORYAHOVITSA("Gorna Oryahovitsa"),
  SVISHTOV("Svishtov"),
  SMOLYAN("Smolyan"),
  PETRICH("Petrich"),
  SANDANSKI("Sandanski"),
  SAMOKOV("Samokov"),
  SCRAP("Scrap"),
  SEVLIEVO("Sevlievo"),
  KARLOVO("Karlovo"),
  NOVA_ZAGORA("Nova Zagora"),
  VELINGRAD("Velingrad"),
  TROJAN("Trojan"),
  AYTOS("Aytos"),
  BOTEVGRAD("Botevgrad"),
  GOTSE_DELCHEV("Gotse Delchev"),
  PESHTERA("Peshtera"),
  HARMANLI("Harmanli"),
  POMORIE("Pomorie"),
  BALCHIK("Balchik"),
  KAVARNA("Kavarna"),
  NESSEBAR("Nessebar"),
  TRYAVNA("Tryavna"),
  BANKYA("Bankya"),
  TUTRAKAN("Tutrakan"),
  VELIKI_PRESLAV("Veliki Preslav"),
  BANSKO("Bansko"),
  HISARYA("Hisarya"),
  VARSHETS("Varshets"),
  TSAREVO("Tsarevo"),
  BELOGRADCHIK("Belogradchik"),
  SOZOPOL("Sozopol"),
  ARDINO("Ardino"),
  SHABLA("Shabla"),
  BATAK("Batak"),
  PRIMORSKO("Primorsko"),
  APRILTSI("Apriltsi"),
  SVETI_VLAS("Sveti Vlas"),
  KOPRIVSHTITSA("Koprivshtitsa"),
  BYALA("Byala"),
  ALFATAR("Alfatar"),
  ANTONOVO("Antonovo"),
  SHIPKA("Shipka"),
  AHTOPOL("Ahtopol"),
  PLISKA("Pliska"),
  KITEN("Kiten"),
  MELNIK("Melnik");

  private final String displayValue;

}
